---
version: 2.1
orbs:
  gh: circleci/github-cli@1.0

jobs:
  create-pr:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - gh/setup
      - gh/clone
      - run:
          command: |
            git checkout -b stage-release
            git config --global user.email "gtadi@astronomer.io"
            git config --global user.name "Goutam Tadi"
            cat\<<EOF>release.txt 
            Stage release
            EOF
            git add release.txt
            git commit -m "new release"
            git push -u origin stage-release
            gh pr create -d --base master --head stage-release --title "Stage release" --body "Hello test Stage release"
          name: Create Pull Request

workflows:
  build:
    jobs:
      - create-pr:
          context: 
            - github_repo
