---
version: 2.1
orbs:
  gh: circleci/github-cli@1.0.3
  slack: circleci/slack@4.4.2

jobs:
  create-pr:
    working_directory: ~/shared-dir
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: ~/shared-dir
      - add_ssh_keys:
          fingerprints:
            - 24:f0:91:e0:f6:03:3a:04:3a:b7:95:1e:00:e5:e2:61
            - c0:62:36:77:1a:4b:e9:5e:bf:c1:aa:2b:1a:43:fb:5a
      - gh/setup
      - gh/clone
      - run:
          command: |
            DATE=$(date +"%Y-%m-%d_%H-%M-%S")
            git checkout -b stage-release-$DATE
            git config --global user.email "gtadi@astronomer.io"
            git config --global user.name "Goutam Tadi"
            cat\<<EOF>release.txt 
            Stage release
            $DATE
            EOF
            git add release.txt
            git commit -m 'Stage Release $DATE'
            git push -u origin HEAD
            PR=$(gh pr create --title "New Stage Release $DATE" --draft --body "New Draft PR for Stage Release $DATE")
            echo $PR > ~/shared-dir/pr
            echo $PR
          name: Create Pull Request
      - persist_to_workspace:
          root: ~/shared-dir
          paths:
            - pr
  notify:
    working_directory: ~/shared-dir
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: ~/shared-dir
      - run:
          name: "set variable"
          command: |
            PR=$(cat ~/shared-dir/pr)
            echo "export PR=$PR" >> $BASH_ENV
            source $BASH_ENV
            echo $PR
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": ":white_check_mark: Created a New Stage Release Draft PR: `$PR`",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: pass

workflows:
  pr-and-notify:
    jobs:
      - create-pr:
          context: 
            - github_repo
      - notify:
          context: slack_astronomer
          requires:
            - create-pr
